name: Import translations from Weblate

on:
  pull_request:
    paths: ['translations/*.yaml']

jobs:
  import:
    runs-on: ubuntu-24.04

    # Only run if the pull request was opened by Weblate's GitHub bot user.
    if: ${{ github.event.sender.id == 1607653 && github.event.pull_request.maintainer_can_modify == true }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          ./.venv/bin/activate
          pip install -r requirements.txt

      - name: Run import translations script
        run: python scripts/import-translations.py

      - name: Run the export translations script
        run: python scripts/export-translations.py

      - name: Create patch containing changes
        run: git diff > sync-translations.patch

      - name: Record pull request head data
        run: |
          echo 'export PR_HEAD_URL="${{ github.event.pull_request.head.repo.clone_url }}"' > git_vars.sh
          echo 'export PR_HEAD_REF="${{ github.event.pull_request.head.ref }}"' >> git_vars.sh
          echo 'export COMMIT_MESSAGE="Import translations from Weblate"' >> git_vars.sh

      - name: Upload data
        uses: actions/upload-artifact@v4
        with:
          name: sync-translations-data
          path: |
            sync-translations.patch
            git_vars.sh
